apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-uber-dep
spec:
  selector:
    matchLabels:
      run: backend-uber-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: backend-uber-dep
    spec:
      imagePullSecrets:
      - name: ndc-mdmjx
      containers:
      - name: backend-uber
        imagePullPolicy: Always
        image: ghcr.io/juu-aix-ynov-campus/backend_uber:latest
        ports:
        - containerPort: 1337
