apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-uber-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: uber-like.ydevops.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: backend-uber-service
          servicePort: 1337
  tls:
  - hosts:
    - uber-like.ydevops.fr
    secretName: jcatania-tls
